steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Compile Elm code, package into slimmer 2nd stage image
    args: ['build', '-t', 'gcr.io/fir-sandbox-326008/site-nginx:latest', '--file', 'Dockerfile', '.']

  - name: 'gcr.io/cloud-builders/docker'
    id: Push up to gcr
    args: ['push', 'gcr.io/fir-sandbox-326008/site-nginx:latest']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    id: Deploy to Cloud Run
    entrypoint: gcloud
    args: [
      'run',
      'deploy',
      'site-nginx',
      '--image',
      'gcr.io/fir-sandbox-326008/site-nginx:latest',
      '--region',
      'us-east4',
      '--min-instances',
      '0',
      '--max-instances',
      '5'
    ]

options:
  pool:
    name: 'projects/fir-sandbox-326008/locations/us-east4/workerPools/fir'
